# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qconnman-ui

# >> macros
# << macros

Summary:    ConnMan GUI
Version:    1.4.4
Release:    1
Group:      Applications/System
License:    LGPL-2.1+
URL:        https://github.com/OSSystems/qconnman-ui
Source0:    %{name}-%{version}.tar.xz
Source100:  qconnman-ui.yaml
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(qconnman)
BuildRequires:  fdupes
BuildRequires:  gcc-c++
BuildRequires:  qtchooser
BuildRequires:  qt5-qttools-linguist
BuildRequires:  desktop-file-utils

%description
ConnMan configuration user interface.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%doc COPYING README.md
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/qconnman/i18n/*
# >> files
# << files
